### PR TITLE
Generate unique temporary file for terraform-docs generation

### LINKED ISSUE #159: Terraform docs generation script fails when temp file exists
The script to generate terraform docs uses an intermediate to pre process files with `awk` as work around of a limitation in the `terraform-docs` tool for terraform version 0.12. The  temporary file created is not a unique file, it always generate the following file. `/tmp/terraform-docs-XXXXXXXXXX.tf` In case  the generate file is not cleared or in recursive usages mode the script fails frequent. 

By removing `.tf` from the template it always will use a unique file

### PR DESCRIPTION
**Pull request by npalm**
## what
*  removing .tf from the template it always will use a unique file

## why
The script to generate terraform docs uses an intermediate to pre process files with awk as work around of a limitation in the terraform-docs tool for terraform version 0.12. The temporary file created is not a unique file, it always generate the following file. /tmp/terraform-docs-XXXXXXXXXX.tf In case the generate file is not cleared or in recursive usages mode the script fails frequent. See also #159 

```
➜  ~ TMP_FILE="$(mktemp /tmp/terraform-docs.XXXXXXXXXX.tf)" && echo $TMP_FILE
mktemp: mkstemp failed on /tmp/terraform-docs.XXXXXXXXXX.tf: File exists
➜  ~ TMP_FILE="$(mktemp /tmp/terraform-docs.XXXXXXXXXX)" && echo $TMP_FILE
/tmp/terraform-docs.UWcXrdbU7D
```

## why
* closes #159

### CODE REVIEW

File: bin/terraform-docs.sh [hunk 1]
```diff
@@ -5,7 +5,7 @@ which terraform 2>&1 >/dev/null || ( echo "terraform not available"; exit 1)
 which terraform-docs 2>&1 >/dev/null || ( echo "terraform-docs not available"; exit 1)
 
 if [[ "`terraform version | head -1`" =~ 0\.12 ]]; then
-    TMP_FILE="$(mktemp /tmp/terraform-docs-XXXXXXXXXX.tf)"
+    TMP_FILE="$(mktemp /tmp/terraform-docs-XXXXXXXXXX)"
```
Comment (osterman) [inline bin/terraform-docs.sh:8]: Please refer to the other pull requests to see how to format the pull request. This change by itself doesn't explain why this would generate a unique temporary file any differently.

**Comment by npalm** [comment]
@osterman added a description as requested. The description was available in #159

**Comment by osterman** [comment]
Thanks @npalm !

**Review by osterman — APPROVED** [review]
